# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jmakwana/onewire/onewire.srcs/sources_1/bd/one_wire/ip/one_wire_processing_system7_0_1/one_wire_processing_system7_0_1.xci
# IP: The module: 'one_wire_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_processing_system7_0_1/one_wire_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jmakwana/onewire/onewire.srcs/sources_1/bd/one_wire/ip/one_wire_processing_system7_0_1/one_wire_processing_system7_0_1.xci
# IP: The module: 'one_wire_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_processing_system7_0_1/one_wire_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
