# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jmakwana/onewire/onewire.srcs/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2.xci
# IP: The module: 'one_wire_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jmakwana/onewire/onewire.srcs/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2.xci
# IP: The module: 'one_wire_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'one_wire_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
