# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/one_wire_constraints.xdc

# Block Designs: bd/one_wire/one_wire.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire || ORIG_REF_NAME==one_wire} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_processing_system7_0_1/one_wire_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_processing_system7_0_1 || ORIG_REF_NAME==one_wire_processing_system7_0_1} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_axi_uartlite_0_2/one_wire_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_axi_uartlite_0_2 || ORIG_REF_NAME==one_wire_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_ps7_0_axi_periph_2/one_wire_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_ps7_0_axi_periph_2 || ORIG_REF_NAME==one_wire_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_rst_ps7_0_50M_2/one_wire_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_rst_ps7_0_50M_2 || ORIG_REF_NAME==one_wire_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_xbar_0/one_wire_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_xbar_0 || ORIG_REF_NAME==one_wire_xbar_0} -quiet] -quiet

# IP: bd/one_wire/ip/one_wire_auto_pc_0/one_wire_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==one_wire_auto_pc_0 || ORIG_REF_NAME==one_wire_auto_pc_0} -quiet] -quiet

# XDC: /home/jmakwana/onewire/onewire.gen/sources_1/bd/one_wire/one_wire_ooc.xdc
